# You can add key value pair here, to create env values.
# for example,
SUNBIRD_REPORTS_DB_HOST: "{{ .Values.global.postgresql.host }}"
SUNBIRD_REPORTS_DB_NAME: "postgres" 
SUNBIRD_REPORTS_DB_PASSWORD: "{{.Values.global.postgresql.postgresqlPassword}}"
SUNBIRD_REPORTS_DB_PORT: "{{.Values.global.postgresql.port}}"
SUNBIRD_REPORTS_DB_USER: "{{ .Values.postgresql.user | default .Values.global.postgresql.postgresqlUser }}"
SUNBIRD_SERVER_PORT: "3030"
SUNBIRD_BASE_REPORT_URL: report
SUNBIRD_REPORTS_TABLE_NAME: report
SUNBIRD_REPORT_SUMMARY_TABLE_NAME: "report_summary"
SUNBIRD_ENV: "https://{{ .Values.global.domain }}"
DEACTIVATE_JOB_API_HOST: http://kong:8000/data/v1/report/jobs/deactivate
DEACTIVATE_JOB_API_KEY: "{{ .Values.global.sunbird_admin_api_token }}"

# 4.10.0

# sunbird_api_auth_token: "{{.Values.global.sunbird_admin_api_token}}"
# sunbird_super_admin_slug: 'sunbird'
# sunbird_portal_auth_server_url: "https://{{.Values.global.domain}}/auth"
# sunbird_portal_auth_server_client: "{{.Values.sunbird_portal_auth_server_client | default "portal"}}"
# sunbird_keycloak_public: "True"
# sunbird_learner_player_url: ""
# sunbird_content_proxy_url: http://knowledge-mw-service:5000
# sunbird_keycloak_realm: ""
# sunbird_cache_store: "memory"
# sunbird_cache_ttl: "1800"
# sunbird_report_sas_expiry_in_minutes: "3600"
# sunbird_dataservice_url: "https://{{.Values.global.domain}}/api/"

## 5.0.0 [commented part not used in newer version
# sunbird_azure_report_container_name: "{{ .Values.global.public_container_name }}/reports" 
# sunbird_azure_account_name: "{{ .Values.global.cloud_storage_access_key }}"
# sunbird_azure_account_key: "{{ .Values.global.cloud_storage_secret_key }}"
SUNBIRD_CLOUD_STORAGE_PROVIDER: "{{ .Values.global.sunbird_cloud_storage_provider }}"
sunbird_cloud_storage_key: "{{ .Values.global.cloud_storage_secret_key }}"
cloud_private_storage_accountname: "{{ .Values.global.cloud_storage_access_key }}"
sunbird_cloud_storage_secret: "{{ .Values.global.cloud_storage_secret_key }}"
sunbird_gcloud_project_id: "{{ .Values.global.cloud_storage_project_id | default "" }}"
cloud_storage_privatereports_bucketname: "{{ .Values.global.public_container_name }}/reports"
cloud_storage_resourceBundle_bucketname: "{{.Values.global.public_container_name | default "labels" }}"
cloud_private_storage_secret: "{{ .Values.global.cloud_storage_secret_key }}"
sunbird_cloud_storage_container: "{{ .Values.global.public_container_name }}/reports"
sunbird_api_auth_token: "{{.Values.global.sunbird_admin_api_token }}"
sunbird_super_admin_slug: 'sunbird'
sunbird_portal_auth_server_url: "https://{{.Values.global.domain}}/auth"
sunbird_portal_auth_server_client: "{{.Values.sunbird_portal_auth_server_client | default "portal" }}"
sunbird_keycloak_public: "True"
sunbird_learner_player_url: ""
sunbird_content_proxy_url: http://knowledge-mw-service:5000
sunbird_keycloak_realm: ""
sunbird_cache_store: "memory"
sunbird_cache_ttl: "1800"
sunbird_report_sas_expiry_in_minutes: "3600"
sunbird_dataservice_url: "https://{{.Values.global.domain}}/api/"
AZURE_STORAGE_ACCOUNT: "{{ .Values.global.cloud_storage_access_key }}"
AZURE_STORAGE_ACCESS_KEY:  "{{ .Values.global.cloud_storage_secret_key }}"