# You can add key value pair here, to create env values.
ACCESS_TOKEN_VALIDITY: {{ .Values.ACCESS_TOKEN_VALIDITY | quote }}
AM_ADMIN_API_ACCESS_BASEPATH: {{ .Values.AM_ADMIN_API_ACCESS_BASEPATH }}
AM_ADMIN_API_ACCESS_KEYCOUNT: {{ .Values.AM_ADMIN_API_ACCESS_KEYCOUNT | quote }}
AM_ADMIN_API_ACCESS_KEYPREFIX: {{ .Values.AM_ADMIN_API_ACCESS_KEYPREFIX }}
AM_ADMIN_API_ACCESS_KEYSTART: {{ .Values.AM_ADMIN_API_ACCESS_KEYSTART | quote }}
AM_ADMIN_API_DESKTOP_DEVICE_BASEPATH: {{ .Values.AM_ADMIN_API_DESKTOP_DEVICE_BASEPATH }}
AM_ADMIN_API_DESKTOP_DEVICE_KEYCOUNT: {{ .Values.AM_ADMIN_API_DESKTOP_DEVICE_KEYCOUNT | quote }}
AM_ADMIN_API_DESKTOP_DEVICE_KEYPREFIX: {{.Values.AM_ADMIN_API_DESKTOP_DEVICE_KEYPREFIX }}
AM_ADMIN_API_DESKTOP_DEVICE_KEYSTART: {{ .Values.AM_ADMIN_API_DESKTOP_DEVICE_KEYSTART | quote }}
AM_ADMIN_API_ENDPOINT: {{ .Values.AM_ADMIN_API_ENDPOINT }}
AM_ADMIN_API_KEYS: {{ .Values.AM_ADMIN_API_KEYS }}
AM_ADMIN_API_MOBILE_DEVICE_BASEPATH: {{ .Values.AM_ADMIN_API_MOBILE_DEVICE_BASEPATH }}
AM_ADMIN_API_MOBILE_DEVICE_KEYCOUNT: {{ .Values.AM_ADMIN_API_MOBILE_DEVICE_KEYCOUNT | quote }}
AM_ADMIN_API_MOBILE_DEVICE_KEYPREFIX: {{ .Values.AM_ADMIN_API_MOBILE_DEVICE_KEYPREFIX }}
AM_ADMIN_API_MOBILE_DEVICE_KEYSTART: {{ .Values.AM_ADMIN_API_MOBILE_DEVICE_KEYSTART | quote }}
AM_ADMIN_API_PORTAL_ANONYMOUS_BASEPATH: {{ .Values.AM_ADMIN_API_PORTAL_ANONYMOUS_BASEPATH }}
AM_ADMIN_API_PORTAL_ANONYMOUS_KEYCOUNT: {{ .Values.AM_ADMIN_API_PORTAL_ANONYMOUS_KEYCOUNT | quote }}
AM_ADMIN_API_PORTAL_ANONYMOUS_KEYPREFIX: {{ .Values.AM_ADMIN_API_PORTAL_ANONYMOUS_KEYPREFIX }}
AM_ADMIN_API_PORTAL_ANONYMOUS_KEYSTART: {{ .Values.AM_ADMIN_API_PORTAL_ANONYMOUS_KEYSTART | quote }}
AM_ADMIN_API_PORTAL_LOGGEDIN_BASEPATH: {{ .Values.AM_ADMIN_API_PORTAL_LOGGEDIN_BASEPATH }}
AM_ADMIN_API_PORTAL_LOGGEDIN_KEYCOUNT: {{ .Values.AM_ADMIN_API_PORTAL_LOGGEDIN_KEYCOUNT | quote }}
AM_ADMIN_API_PORTAL_LOGGEDIN_KEYPREFIX: {{ .Values.AM_ADMIN_API_PORTAL_LOGGEDIN_KEYPREFIX }}
AM_ADMIN_API_PORTAL_LOGGEDIN_KEYSTART: {{ .Values.AM_ADMIN_API_PORTAL_LOGGEDIN_KEYSTART | quote }}
DEFAULT_CONSUMER_GROUP: {{ .Values.DEFAULT_CONSUMER_GROUP }}
EMBED_ROLE: {{ .Values.EMBED_ROLE | quote }}
ENDPOINTS_HEALTH_ID: {{ .Values.ENDPOINTS_HEALTH_ID }}
ENDPOINTS_HEALTH_SENSITIVE: {{ .Values.ENDPOINTS_HEALTH_SENSITIVE | quote }}
ENDPOINTS_METRICS_ID: {{ .Values.ENDPOINTS_METRICS_ID }}
ENDPOINTS_METRICS_SENSITIVE: {{ .Values.ENDPOINTS_METRICS_SENSITIVE | quote }}
JAVA_OPTS: {{ .Values.JAVA_OPTS }}
LEARNER_API_AUTH_KEY: {{ .Values.global.adminutil_learner_api_auth_key }}
LEARNER_BASE_API_URL: {{ .Values.LEARNER_BASE_API_URL }}
REFRESH_TOKEN_DOMAIN: "https://{{ .Values.global.domain }}/auth/realms/sunbird"
REFRESH_TOKEN_LOG_OLDER_THAN: {{ .Values.REFRESH_TOKEN_LOG_OLDER_THAN | quote }}
REFRESH_TOKEN_OFFLINE_VALIDITY: {{ .Values.REFRESH_TOKEN_OFFLINE_VALIDITY | quote }}
REFRESH_TOKEN_PRELOAD: {{ .Values.REFRESH_TOKEN_PRELOAD | quote }}
REFRESH_TOKEN_PUBLIC_BASEPATH: {{ .Values.REFRESH_TOKEN_PUBLIC_BASEPATH }}
REFRESH_TOKEN_PUBLIC_KEYPREFIX: {{ .Values.REFRESH_TOKEN_PUBLIC_KEYPREFIX }}
SERVER_PORT: {{ .Values.SERVER_PORT | quote }}
SPRING_PROFILES_ACTIVE: {{ .Values.SPRING_PROFILES_ACTIVE }}