PORT: "{{ .Values.port }}"
QR_TYPE: "{{ .Values.QR_TYPE }}"
CERTIFICATE_DOMAIN_URL: "https://{{ .Values.global.domain }}"
CERTIFICATE_PUBLIC_KEY: "{{ .Values.global.CERTIFICATE_PUBLIC_KEY }}"
CERTIFICATE_PRIVATE_KEY: "{{ .Values.global.CERTIFICATE_PRIVATE_KEY }}"
JAVA_OPTIONS: "{{ .Values.java_options }}"