JAVA_OPTIONS: "{{ .Values.java_options }}"
_JAVA_OPTIONS: "{{ .Values.log4j_java_options }}"
sunbird_sso_url: "https://{{ .Values.global.domain }}/auth/"
sunbird_sso_realm: "{{ .Values.sunbird_sso_realm }}"
sunbird_sso_username: "{{ .Values.sunbird_sso_username }}"
sunbird_sso_password: "{{ .Values.sunbird_sso_password }}"
sunbird_sso_client_id: "{{ .Values.sunbird_sso_client_id }}"
sunbird_sso_client_secret: "{{ .Values.sunbird_sso_client_secret }}{{ .Values.global.random_string }}"
sunbird_es_host: "{{ .Values.global.elasticsearch.host }}"
sunbird_es_port: "{{ .Values.global.elasticsearch.port }}"
sunbird_cassandra_username: "{{ .Values.sunbird_cassandra_username }}"
sunbird_cassandra_password: "{{ .Values.sunbird_cassandra_password }}"
actor_hostname: "{{ .Values.actor_hostname }}"
bind_hostname: "{{ .Values.bind_hostname }}"
ekstep_authorization: "{{ .Values.global.sunbird_admin_api_token }}"
sunbird_pg_host: "{{ .Values.global.postgresql.host }}"
sunbird_pg_port: "{{ .Values.global.postgresql.port }}"
sunbird_pg_db: "{{ .Values.sunbird_pg_db }}"
sunbird_pg_user: "{{ .Values.global.postgresql.postgresqlUsername }}"
sunbird_pg_password: "{{ .Values.global.postgresql.core_vault_postgres_password }}"
sunbird_installation: "{{ .Values.global.env }}"
sunbird_analytics_api_base_url: "{{ .Values.sunbird_analytics_api_base_url }}"
sunbird_search_service_api_base_url: "{{ .Values.sunbird_search_service_api_base_url }}"
content_service_base_url: "{{ .Values.content_service_url }}"
content_read_url: "{{ .Values.content_read_url }}"
sunbird_group_service_api_base_url: "{{ .Values.sunbird_group_service_api_base_url }}"
sunbird_mail_server_host: "{{ .Values.global.mail_server_host }}"
sunbird_mail_server_port: "{{ .Values.global.mail_server_port }}"
sunbird_mail_server_username: "{{ .Values.global.mail_server_username }}"
sunbird_mail_server_password: "{{ .Values.global.mail_server_password }}"
sunbird_mail_server_from_email: "{{ .Values.global.mail_server_from_email }}"
sunbird_encryption_key: "{{ .Values.global.random_string }}"
sunbird_encryption_mode: "{{ .Values.sunbird_encryption_mode }}"
sunbird_account_name: "{{ .Values.global.cloud_storage_access_key }}"
sunbird_account_key: "{{ .Values.global.cloud_storage_secret_key }}"
sunbird_quartz_mode: "{{ .Values.sunbird_quartz_mode }}"
sunbird_web_url: "{{ .Values.global.domain }}"
sunbird_msg_91_auth: "{{ .Values.global.sunbird_msg_91_auth }}"
sunbird_msg_sender: "{{ .Values.global.sunbird_msg_sender }}"
sunbird_installation_email: "{{ .Values.sunbird_installation_email }}"
sunbird_cassandra_host: "{{ .Values.global.cassandra.host }}"
sunbird_cassandra_port: "{{ .Values.global.cassandra.port }}"
sunbird_cassandra_consistency_level: "{{ .Values.global.cassandra.consistency_level }}"
sunbird_mw_system_host: "{{ .Values.sunbird_mw_system_host }}"
sunbird_mw_system_port: "{{ .Values.sunbird_mw_system_port }}"
background_actor_provider: "{{ .Values.background_actor_provider }}"
api_actor_provider: "{{ .Values.api_actor_provider }}"
sunbird_badger_baseurl: "{{ .Values.sunbird_badger_baseurl }}"
sunbird_remote_req_router_path: "{{ .Values.sunbird_remote_req_router_path }}"
sunbird_remote_bg_req_router_path: "{{ .Values.sunbird_remote_bg_req_router_path }}"
sunbird_api_base_url: "{{ .Values.sunbird_api_base_url }}"
sunbird_authorization: "{{ .Values.global.sunbird_admin_api_token }}"
telemetry_pdata_id: "{{ .Values.global.env }}.sunbird.learning.service"
telemetry_pdata_pid: "{{ .Values.telemetry_pdata_pid }}"
sunbird_telemetry_base_url: "{{ .Values.sunbird_telemetry_base_url }}"
telemetry_queue_threshold_value: "{{ .Values.telemetry_queue_threshold_value }}"
sunbird_default_channel: "{{ .Values.sunbird_default_channel}}"
sunbird_api_mgr_base_url: "{{ .Values.sunbird_api_mgr_base_url }}"
sunbird_cs_base_url: "{{ .Values.sunbird_api_base_url }}"
sunbird_cs_search_path: "{{ .Values.sunbird_cs_search_path }}"
sunbird_env_logo_url: "{{ .Values.sunbird_env_logo_url }}"
sunbird_user_bulk_upload_size: "{{ .Values.sunbird_user_bulk_upload_size }}"
sunbird_installation_display_name: "{{ .Values.sunbird_app_name }} {{ .Values.global.env }}"
sunbird_app_name: {{ .Values.sunbird_app_name }}
sunbird_registry_service_baseurl: {{ .Values.sunbird_registry_service_baseurl }}
sunbird_open_saber_bridge_enable: "{{ .Values.sunbird_open_saber_bridge_enable }}"
sunbird_environment: "{{ .Values.global.env }}"
sunbird_instance: "{{ .Values.global.env }}"
sunbird_email_max_recipients_limit: "{{ .Values.sunbird_email_max_recipients_limit }}"
sunbird_url_shortner_access_token: "{{ .Values.core_vault_sunbird_url_shortner_access_token }}"
sunbird_url_shortner_enable: "{{ .Values.sunbird_url_shortner_enable }}"
sunbird_user_profile_field_default_visibility: "{{ .Values.sunbird_user_profile_field_default_visibility }}"
sunbird_keycloak_required_action_link_expiration_seconds: "{{ .Values.sunbird_keycloak_required_action_link_expiration_seconds }}"
sunbird_course_batch_notification_enabled: "{{ .Values.sunbird_course_batch_notification_enabled }}"
sunbird_course_batch_notification_signature: "{{ .Values.sunbird_course_batch_notification_signature }}"
sunbird_otp_expiration: "{{ .Values.sunbird_otp_expiration }}"
sunbird_otp_length: "{{ .Values.sunbird_otp_length }}"
sunbird_content_cloud_storage_container: "{{ .Values.global.public_container_name }}"
sunbird_time_zone: "{{ .Values.sunbird_time_zone }}"
sunbird_health_check_enable: "{{ .Values.sunbird_health_check_enable }}"
sunbird_keycloak_user_federation_provider_id: "{{ .Values.sunbird_keycloak_user_federation_provider_id }}"
sunbird_gzip_enable: "{{ .Values.sunbird_gzip_enable }}"
sunbird_gzip_size_threshold: "{{ .Values.sunbird_gzip_size_threshold }}"
sunbird_analytics_blob_account_name: "{{ .Values.global.cloud_storage_access_key }}"
sunbird_analytics_blob_account_key: "{{ .Values.global.cloud_storage_secret_key }}"
sunbird_cache_enable: "{{ .Values.sunbird_cache_enable }}"
sunbird_redis_host: "{{ .Values.global.redis.host }}"
sunbird_redis_port: "{{ .Values.global.redis.port }}"
sunbird_user_org_api_base_url: "{{ .Values.sunbird_user_org_api_base_url }}"
kafka_topics_instruction: "{{ .Values.global.env }}.coursebatch.job.request"
kafka_urls: "{{ .Values.global.kafka.host }}:{{ .Values.global.kafka.port }}"
kafka_topics_certificate_instruction: "{{ .Values.global.env }}.issue.certificate.request"
kafka_assessment_topic: "{{ .Values.global.env }}.telemetry.assess"
kafka_topics_contentstate_invalid: "{{ .Values.global.env }}.contentstate.invalid"
kafka_enrolment_sync_topic: "{{ .Values.global.env }}.batch.enrolment.sync.request"
sunbird_cert_service_base_url: "{{ .Values.sunbird_cert_service_base_url }}"
learning_service_base_url: "{{ .Values.learning_service_base_url }}"
sunbird_user_search_cretordetails_fields: "{{ .Values.sunbird_user_search_cretordetails_fields }}"
sunbird_user_service_api_base_url: "{{ .Values.sunbird_user_service_api_base_url }}"
limit_managed_user_creation: "{{ .Values.limit_managed_user_creation }}"
managed_user_limit: "{{ .Values.managed_user_limit }}"
sunbird_user_qrcode_courses_limit: "{{ .Values.sunbird_user_qrcode_courses_limit }}"
accesstoken.publickey.basepath: "{{ .Values.keys_basepath }}"
learning.content.props.to.add: "{{ .Values.learning_content_props_to_add }}"
group_activity_agg_cache_ttl: "{{ .Values.group_activity_agg_cache_ttl }}"
group_activity_agg_cache_enable: "{{ .Values.group_activity_agg_cache_enable }}"
redis.connection.max: "{{ .Values.redis_connection_max }}"
redis.connection.idle.max: "{{ .Values.redis_connection_idle_max }}"
redis.connection.idle.min: "{{ .Values.redis_connection_idle_min }}"
redis.connection.minEvictableIdleTimeSeconds: "{{ .Values.redis_connection_minEvictableIdleTimeSeconds }}"
redis.connection.timeBetweenEvictionRunsSeconds: "{{ .Values.redis_connection_timeBetweenEvictionRunsSeconds }}"
redis.experimentIndex: "{{ .Values.redis_experimentIndex }}"
redis.dbIndex: "{{ .Values.redis_dbIndex }}"
user_enrolments_response_cache_enable: "{{ .Values.user_enrolments_response_cache_enable }}"
user_enrolments_response_cache_ttl: "{{ .Values.user_enrolments_response_cache_ttl }}"
druid_proxy_api_host: "{{ .Values.global.druid.host }}"
druid_proxy_api_port: "{{ .Values.druid_proxy_api_port }}"
druid_proxy_api_endpoint: "{{ .Values.druid_proxy_api_endpoint }}"
collection_summary_agg_data_source: "{{ .Values.collection_summary_agg_data_source }}"
collection_summary_agg_cache_ttl: "{{ .Values.collection_summary_agg_cache_ttl }}"
enrollment_list_size: "{{ .Values.enrollment_list_size }}"
sunbird_cloud_service_provider: "{{ .Values.global.cloud_storage_provider }}"
isMultiDCEnabled: "{{ .Values.isMultiDCEnabled }}"
cloud_storage_base_url: https://{{ .Values.global.object_storage_endpoint }}
cloud_storage_cname_url: https://{{ .Values.global.object_storage_endpoint }}
cloud_storage_dial_bucketname: {{ .Values.global.public_container_name }}
cloud_storage_path_prefix_dial: "{{ .Values.cloud_storage_path_prefix_dial }}"
cloud_store_base_path_placeholder: {{ .Values.cloud_store_base_path_placeholder }}
sunbird_dial_service_base_url: {{ .Values.sunbird_dial_service_base_url }}
sunbird_dial_service_search_url: {{ .Values.sunbird_dial_service_search_url }}
