  PORT: "{{ .Values.PORT }}"
  QR_TYPE: "{{ .Values.QR_TYPE }}"
  CERTIFICATE_DOMAIN_URL: "https://{{ .Values.global.domain }}"
  CERTIFICATE_PUBLIC_KEY: "{{ .Values.CERTIFICATESIGN_PUBLIC_KEY }}"
  CERTIFICATE_PRIVATE_KEY: |-
    "{{ .Values.CERTIFICATESIGN_PRIVATE_KEY }}"
  SIGNING_KEY_TYPE: "{{ .Values.SIGNING_KEY_TYPE }}"
  CACHE_CONTEXT_URLS: "{{ .Values.global.domain }}/schema/v1_context.json, {{ .Values.global.domain }}/schema/sunbird_context.json, {{ .Values.global.domain }}/schema/credential_template.json }}"
  JAVA_OPTIONS: "{{ .Values.java_options }}"